Repository qonto/ember-amount-input, pull requests merged in 2022-07, with the labels that each got.

#360 Update docs to allow further dependency updates
  config/ember-try.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/app/pods/application/route.js
  tests/dummy/app/pods/docs/components/amount-input/controller.js
  tests/dummy/app/pods/docs/components/amount-input/template.hbs
  tests/dummy/app/pods/docs/template.hbs
  tests/dummy/app/routes/docs/index.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/docs.hbs
  tests/dummy/app/templates/docs/components/amount-input.md
  tests/dummy/app/templates/docs/installation.md
  tests/dummy/app/templates/index.hbs
  tests/dummy/config/environment.js
  yarn.lock
Labels: dependencies, documentation

#368 Use angle bracket syntax for amount-input
  addon/components/amount-input.js
  tests/dummy/app/templates/docs/components/amount-input.md
  tests/integration/components/amount-input/component-test.js
Labels: documentation

#367 Document the @disabled argument
  addon/components/amount-input.js
Labels: documentation

#336 CI: Automate release
  .eslintrc.js
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .release-it.js
  package.json
  yarn.lock
Labels: internal

#371 Update release instructions and link to docs
  README.md
  RELEASE.md
Labels: documentation
